## Ch. 4 NumPy Basics

numpy has better ability to handle calculation of large datasets

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 39.9 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.29 s


### 4.1 The numpy ndarray
N-dimensional array object

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[-1.80547282, -1.34540399, -1.43054525],
       [-0.46093254,  1.9792658 , -0.74204426]])

In [9]:
data * 10

array([[-18.05472822, -13.45403988, -14.30545249],
       [ -4.60932535,  19.79265801,  -7.42044261]])

In [10]:
data + data 

array([[-3.61094564, -2.69080798, -2.8610905 ],
       [-0.92186507,  3.9585316 , -1.48408852]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

#### Creating ndarrays

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1=np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3,4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[1.07838846e-311, 1.07838846e-311],
        [1.07838846e-311, 1.07838846e-311],
        [1.07838846e-311, 1.07838846e-311]],

       [[1.07838846e-311, 1.07838846e-311],
        [1.07838846e-311, 1.07838846e-311],
        [1.07838846e-311, 1.07838846e-311]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Data types for ndarrays

In [28]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [37]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [40]:
numeric_strings.dtype

dtype('S4')

In [41]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [42]:
int_array = np.arange(10)

In [43]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [50]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
empty_unit32 = np.empty(8, dtype = 'u4')

In [49]:
empty_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

#### Arithmetic with numpy arrays

In [51]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [52]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [53]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [54]:
arr - arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [56]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [57]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [58]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [59]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### Basic Indexing and Slicing

In [60]:
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
arr_slice = arr[5:8]

In [67]:
arr_slice

array([12, 12, 12])

In [68]:
arr_slice[1] = 12345

In [69]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [70]:
arr_slice[:] = 64

In [71]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [72]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [73]:
arr2d[2]

array([7, 8, 9])

In [75]:
arr2d[0][2]

3

In [77]:
arr2d[0, 2]

3

In [87]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [88]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
old_values = arr3d[0].copy()

In [91]:
arr3d[0] = 42

In [92]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [93]:
arr3d[0] = old_values

In [94]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [95]:
arr3d[1, 0]

array([7, 8, 9])

In [96]:
x = arr3d[1]

In [97]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [98]:
x[0]

array([7, 8, 9])

#### Indexing with slices

In [99]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [100]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [101]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [105]:
arr2d[1, :2]

array([4, 5])

In [106]:
arr2d[:2, 2]

array([3, 6])

In [107]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

#### Boolean Indexing

In [108]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [109]:
data = np.random.randn(7, 4)

In [110]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [111]:
data

array([[-1.12831402,  0.72903434,  0.19211456, -0.12623334],
       [-0.2534676 , -1.17070514,  0.36169293,  1.20276534],
       [ 0.58159344,  0.25913622, -0.29297831,  2.31486658],
       [ 1.21194431, -1.30448667, -0.53429715, -0.93876804],
       [ 1.80016905,  0.04028854, -0.30717442,  0.36491752],
       [-0.14034257,  0.96555441, -1.17497774,  0.59763706],
       [ 1.03548764, -0.0223518 ,  0.7308962 , -2.12392643]])

In [112]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [113]:
data[names == 'Bob']

array([[-1.12831402,  0.72903434,  0.19211456, -0.12623334],
       [ 1.21194431, -1.30448667, -0.53429715, -0.93876804]])

In [114]:
data[names == 'Bob', 2:]

array([[ 0.19211456, -0.12623334],
       [-0.53429715, -0.93876804]])

In [115]:
data[names == 'Bob', 3]

array([-0.12623334, -0.93876804])

In [116]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [117]:
data[~(names == 'Bob')]

array([[-0.2534676 , -1.17070514,  0.36169293,  1.20276534],
       [ 0.58159344,  0.25913622, -0.29297831,  2.31486658],
       [ 1.80016905,  0.04028854, -0.30717442,  0.36491752],
       [-0.14034257,  0.96555441, -1.17497774,  0.59763706],
       [ 1.03548764, -0.0223518 ,  0.7308962 , -2.12392643]])

In [118]:
cond = names == 'Bobs'

In [120]:
cond

array([False, False, False, False, False, False, False])

In [121]:
data[~cond]

array([[-1.12831402,  0.72903434,  0.19211456, -0.12623334],
       [-0.2534676 , -1.17070514,  0.36169293,  1.20276534],
       [ 0.58159344,  0.25913622, -0.29297831,  2.31486658],
       [ 1.21194431, -1.30448667, -0.53429715, -0.93876804],
       [ 1.80016905,  0.04028854, -0.30717442,  0.36491752],
       [-0.14034257,  0.96555441, -1.17497774,  0.59763706],
       [ 1.03548764, -0.0223518 ,  0.7308962 , -2.12392643]])

In [122]:
mask = (names == 'Bob') | (names == 'Will')

In [123]:
mask

array([ True, False,  True,  True,  True, False, False])

In [125]:
data

array([[-1.12831402,  0.72903434,  0.19211456, -0.12623334],
       [-0.2534676 , -1.17070514,  0.36169293,  1.20276534],
       [ 0.58159344,  0.25913622, -0.29297831,  2.31486658],
       [ 1.21194431, -1.30448667, -0.53429715, -0.93876804],
       [ 1.80016905,  0.04028854, -0.30717442,  0.36491752],
       [-0.14034257,  0.96555441, -1.17497774,  0.59763706],
       [ 1.03548764, -0.0223518 ,  0.7308962 , -2.12392643]])

In [126]:
data[mask]

array([[-1.12831402,  0.72903434,  0.19211456, -0.12623334],
       [ 0.58159344,  0.25913622, -0.29297831,  2.31486658],
       [ 1.21194431, -1.30448667, -0.53429715, -0.93876804],
       [ 1.80016905,  0.04028854, -0.30717442,  0.36491752]])

In [127]:
data[data < 0] = 0

In [128]:
data

array([[0.        , 0.72903434, 0.19211456, 0.        ],
       [0.        , 0.        , 0.36169293, 1.20276534],
       [0.58159344, 0.25913622, 0.        , 2.31486658],
       [1.21194431, 0.        , 0.        , 0.        ],
       [1.80016905, 0.04028854, 0.        , 0.36491752],
       [0.        , 0.96555441, 0.        , 0.59763706],
       [1.03548764, 0.        , 0.7308962 , 0.        ]])

In [129]:
data[names != 'Joe'] = 7

In [130]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.36169293, 1.20276534],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.96555441, 0.        , 0.59763706],
       [1.03548764, 0.        , 0.7308962 , 0.        ]])

#### Fancy Indexing

In [131]:
arr = np.empty((8, 4))

In [132]:
arr

array([[1.07839256e-311, 1.07839259e-311, 1.07839259e-311,
        1.07839265e-311],
       [1.07839265e-311, 1.07839265e-311, 1.07839266e-311,
        1.07839266e-311],
       [1.07839266e-311, 1.07839265e-311, 1.07839265e-311,
        1.07839265e-311],
       [1.07839265e-311, 1.07839266e-311, 1.07839266e-311,
        1.07839266e-311],
       [1.07839266e-311, 1.07839266e-311, 1.07839266e-311,
        1.07839266e-311],
       [1.07839266e-311, 1.07839266e-311, 1.07839266e-311,
        1.07839266e-311],
       [1.07839266e-311, 1.07839266e-311, 1.07839266e-311,
        1.07839266e-311],
       [1.07839266e-311, 1.07839266e-311, 1.07839266e-311,
        1.07839266e-311]])

In [133]:
for i in range(8):
    arr[i] = i

In [134]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [135]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [136]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [139]:
arr = np.arange(32).reshape((8, 4))

In [141]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [142]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [145]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### Transposing Arrays and Swapping Axes

In [146]:
arr = np.arange(15).reshape((3, 5))

In [147]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [148]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [149]:
arr = np.random.randn(6, 3)

In [150]:
arr

array([[-3.62793665,  0.61384863, -1.68096723],
       [ 0.52833607, -0.33380433,  2.17485386],
       [ 1.58622974, -0.03615577, -0.80217629],
       [ 0.24861198, -1.31524065, -0.62078504],
       [-0.85597909,  0.34786915,  0.34243732],
       [-1.20325054,  0.68048288,  0.26743845]])

In [151]:
np.dot(arr.T, arr)

array([[18.19950813, -3.90426084,  5.20581123],
       [-3.90426084,  2.80347056, -0.61123938],
       [ 5.20581123, -0.61123938,  8.77328764]])

In [152]:
arr = np.arange(16).reshape((2, 2, 4))

In [153]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [154]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [155]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [157]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 4.2 Universal Functions: Fast Element-Wise Array Functions

In [158]:
arr = np.arange(10)

In [159]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [160]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [161]:
x = np.random.randn(8)

In [162]:
y = np.random.randn(8)

In [163]:
x

array([-0.02386662, -0.78189437,  0.64033835, -0.45927435, -0.1378754 ,
        0.05643153,  1.38957878,  0.76417939])

In [164]:
y

array([-0.35126671, -0.40952572, -0.11797578,  1.14277136,  0.26034457,
        0.6400954 , -0.97271692, -1.08401596])

In [165]:
np.maximum(x, y)

array([-0.02386662, -0.40952572,  0.64033835,  1.14277136,  0.26034457,
        0.6400954 ,  1.38957878,  0.76417939])

In [166]:
arr = np.random.randn(7) * 5

In [167]:
arr

array([  5.15131089,  -1.41408185,  -1.61808687, -10.87498917,
         1.1836911 ,  -3.183002  ,   2.1166084 ])

In [168]:
remainder, whole_part = np.modf(arr)

In [170]:
remainder

array([ 0.15131089, -0.41408185, -0.61808687, -0.87498917,  0.1836911 ,
       -0.183002  ,  0.1166084 ])

In [171]:
whole_part

array([  5.,  -1.,  -1., -10.,   1.,  -3.,   2.])

In [172]:
arr

array([  5.15131089,  -1.41408185,  -1.61808687, -10.87498917,
         1.1836911 ,  -3.183002  ,   2.1166084 ])

In [173]:
np.sqrt(arr)

array([2.26964995,        nan,        nan,        nan, 1.08797569,
              nan, 1.45485683])

In [174]:
np.sqrt(arr, arr)

array([2.26964995,        nan,        nan,        nan, 1.08797569,
              nan, 1.45485683])

In [175]:
arr

array([2.26964995,        nan,        nan,        nan, 1.08797569,
              nan, 1.45485683])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])